import {
  Alert,
  Box,
  Button,
  Dialog,
  Paper,
  Stack,
  Typography,
} from "@mui/material";
import hitsData from "../data/hits.json";
import SendIcon from "@mui/icons-material/Send";
import { useState } from "react";

/** Get the Saturday on or before the given date as M/D/YYYY */
function getWeekStart(): string {
  const date = new Date();
  const dayIndex = date.getDay(); // 0=Sun, 1=Mon, ... 6=Sat
  const saturdayOffset = dayIndex >= 6 ? 0 : -(dayIndex + 1);
  const saturday = new Date(date);
  saturday.setDate(date.getDate() + saturdayOffset);
  return `${saturday.getMonth() + 1}/${saturday.getDate()}/${saturday.getFullYear()}`;
}

/** Get the Friday following the week start Saturday */
function getWeekEnd(weekStart: string): string {
  const parts = weekStart.split("/");
  const sat = new Date(
    parseInt(parts[2]),
    parseInt(parts[0]) - 1,
    parseInt(parts[1]),
  );
  const fri = new Date(sat);
  fri.setDate(sat.getDate() + 6);
  return `${fri.getMonth() + 1}/${fri.getDate()}`;
}

function getSubject(weekStart: string): string {
  const parts = weekStart.split("/");
  const satLabel = `${parts[0]}/${parts[1]}`;
  const friLabel = getWeekEnd(weekStart);
  return `${satLabel} - ${friLabel}`;
}

function SubmitWeeklyHits() {
  const weekStr = getWeekStart();
  const week = hitsData.find((w) => w.week === weekStr) ?? null;

  const weekdays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"];

  const [isSubmitting, setIsSubmitting] = useState(false);

  async function handleSubmit() {
    const res = await fetch("/api/send-email", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        subject: `HMR ${getSubject(weekStr)}`,
        text: `Hits:\n${week?.hits.map((hit) => `   •   ${hit.task}: [${hit.time} hours]`).join("\n")}\n\nTotal: ${week?.total} hours\n\n\n\nThis email was automatically generated by the Dagan's personal app.`,
      }),
    });
    if (!res.ok) {
      console.error("Failed to send:", await res.text());
    }
    setIsSubmitting(false);
  }

  return (
    <>
      <Typography variant="h4" sx={{ mb: 2 }}>
        Submit Weekly Hits
      </Typography>

      {!week ? (
        <Alert severity="info" sx={{ mt: 2 }}>
          No data found for the week of {weekStr}. Please enter day hits first.
        </Alert>
      ) : (
        <>
          {weekdays.map((day) => {
            const dayHits = week.days[day as keyof typeof week.days];
            return (
              <div key={day}>
                <Typography variant="h6">{day}</Typography>
                <ul>
                  {dayHits && dayHits.length > 0 ? (
                    dayHits.map((hit) => (
                      <li key={hit.key}>
                        <Typography variant="body2">
                          {hit.task} - {hit.time} hours
                        </Typography>
                      </li>
                    ))
                  ) : (
                    <Alert severity="info">No hits entered for {day}.</Alert>
                  )}
                </ul>
              </div>
            );
          })}

          <Typography variant="h6">Hits</Typography>

          <ul>
            {week.hits.map((hit) => (
              <li key={hit.key}>
                <Typography variant="body2">
                  {hit.task} - {hit.time} hours
                </Typography>
              </li>
            )) ?? <Alert severity="info">No hits entered for this week.</Alert>}
          </ul>

          <Typography variant="body1" sx={{ mb: 2 }}>
            Total: {week.total} hours
          </Typography>

          <Button
            variant="outlined"
            fullWidth
            size="large"
            endIcon={<SendIcon />}
            onClick={() => setIsSubmitting(true)}
          >
            Submit
          </Button>

          <Dialog open={isSubmitting} onClose={() => setIsSubmitting(false)}>
            <Box
              sx={{ p: 3, display: "flex", flexDirection: "column", gap: 2 }}
            >
              <Typography variant="h6">Confirm Submission</Typography>

              <Typography variant="body1">
                Are you sure you want to submit your hits for the week of{" "}
                {getSubject(weekStr)}?
              </Typography>

              <Paper sx={{ p: 2, whiteSpace: "pre-line" }}>
                {`HMR ${getSubject(weekStr)}\n\n\nHits:\n${week?.hits
                  .map((hit) => `   •   ${hit.task}: [${hit.time} hours]`)
                  .join(
                    "\n",
                  )}\n\nTotal: ${week?.total} hours\n\n\n\nThis email was automatically generated by Dagan's personal app.`}
              </Paper>

              <Stack
                direction="row"
                spacing={2}
                sx={{ justifyContent: "flex-end" }}
              >
                <Button onClick={() => setIsSubmitting(false)}>Cancel</Button>

                <Button variant="contained" onClick={handleSubmit}>
                  Confirm
                </Button>
              </Stack>
            </Box>
          </Dialog>
        </>
      )}
    </>
  );
}

export default SubmitWeeklyHits;
